##poisson_CNN docker image for Nvidia GPUs on amd64 platforms
FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu18.04

RUN apt update && apt install -y git cmake openmpi-bin libopenmpi-dev python3 python3-pip wget

RUN cd /
RUN pip3 install --upgrade pip
RUN pip3 install jupyterlab			\
    	 	 tensorflow-gpu==2.4		\
		 tensorflow-probability==0.12.2	\
		 matplotlib			\
		 scipy				\
		 cython				\
		 pyamg
RUN git clone https://github.com/aligirayhanozbay/poisson_CNN.git
RUN cd poisson_CNN && pip3 install --no-deps -e .

RUN cd / && wget https://github.com/NVIDIA/AMGX/archive/refs/tags/v2.2.0.tar.gz && tar xvf v2.2.0.tar.gz && mv /AMGX-2.2.0 /AMGX
RUN mkdir /AMGX/build
RUN cd /AMGX/build && cmake ../ && make -j $(nproc) all

RUN cd / && git clone https://github.com/shwina/pyamgx && cd pyamgx && export AMGX_DIR=/AMGX/ && pip3 install .
ENV AMGX_DIR "/AMGX/"
