FROM ibmcom/tensorflow-ppc64le:2.2.0-gpu-py3-jupyter

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install -y --no-install-recommends git cmake openmpi-bin libopenmpi-dev cuda-*-dev*10-1
RUN pip3 install tensorflow_probability

RUN cd / && git clone https://github.com/aligirayhanozbay/poisson_CNN.git
RUN cd /poisson_CNN && pip3 install -e . 

RUN cd / && git clone https://github.com/NVIDIA/AMGX
RUN mkdir /AMGX/build
RUN cd /AMGX/build && cmake ../ && make -j160 all
RUN cd / && git clone https://github.com/shwina/pyamgx && cd pyamgx && export AMGX_DIR=/AMGX/ && pip3 install cython && pip3 install .
ENV AMGX_DIR=/AMGX/
